apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  env.ts: |-
    window.__env = {
      apiUrl: "https://{{ .Values.backend_url }}",
      socketUrl: "wss://{{ .Values.backend_url }}"
    };

